function txt = textNW(ax,s)
% Display text in the northwest corner of a chart
  txt = text(ax, 0.01, 0.90, s,...
    'Units','Normalized',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'Interpreter','none');
end